name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@3.6.0

      - name: Setup Node.js
        uses: actions/setup-node@3.8.1
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build App (Electron)
        run: npm run electron:build

      - name: Show Root Dir
        run: dir

      - name: Show Dist Dir
        run: dir dist

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@3.1.3
        with:
          name: windows-exe
          path: |
            dist/*.exe
            dist/*.nsis.zip
